name: FastAsyncVoxelSniper
main: com.boydti.fawe.bukkit.favs.Favs
version: ${version}
description: Fast Async VoxelSniper
authors: [ Empire92 ]
loadbefore: [ WorldEdit,VoxelSniper ]
load: STARTUP
database: false
softdepend: [ FastAsyncWorldEdit ]
#softdepend: [WorldGuard, PlotSquared, MCore, Factions, GriefPrevention, Residence, Towny, PlotMe, PreciousStones]
commands:
  '/p':
    description: VoxelSniper perform command
    aliases: [ perform,/perform ]
  '/d':
    description: VoxelSniper default command
    aliases: [ default,/default ]
permissions:
  fawe.voxelbrush:
    default: op
    children:
      voxelsniper.brush.ball: true
      voxelsniper.brush.biome: true
      voxelsniper.brush.blendball: true
      voxelsniper.brush.blenddisc: true
      voxelsniper.brush.blendvoxel: true
      voxelsniper.brush.blendvoxeldisc: true
      voxelsniper.brush.blob: true
      voxelsniper.brush.blockreset: true
      voxelsniper.brush.blockresetsurface: true
      voxelsniper.brush.canyon: true
      voxelsniper.brush.canyonselection: true
      voxelsniper.brush.checkervoxeldisc: true
      voxelsniper.brush.cleansnow: true
      voxelsniper.brush.clonestamp: true
      voxelsniper.brush.copypasta: true
      voxelsniper.brush.cylinder: true
      voxelsniper.brush.disc: true
      voxelsniper.brush.discface: true
      voxelsniper.brush.dome: true
      voxelsniper.brush.drain: true
      voxelsniper.brush.ellipse: true
      voxelsniper.brush.ellipsoid: true
      voxelsniper.brush.eraser: true
      voxelsniper.brush.erode: true
      voxelsniper.brush.extrude: true
      voxelsniper.brush.filldown: true
      voxelsniper.brush.flatocean: true
      voxelsniper.brush.heatray: true
      voxelsniper.brush.jaggedline: true
      voxelsniper.brush.line: true
      voxelsniper.brush.move: true
      voxelsniper.brush.ocean: true
      voxelsniper.brush.overlay: true
      voxelsniper.brush.pull: true
      voxelsniper.brush.randomerode: true
      voxelsniper.brush.ring: true
      voxelsniper.brush.rot2d: true
      voxelsniper.brush.rot2dvert: true
      voxelsniper.brush.rot3d: true
      voxelsniper.brush.ruler: true
      voxelsniper.brush.scanner: true
      voxelsniper.brush.set: true
      voxelsniper.brush.setredstoneflip: true
      voxelsniper.brush.setredstonerotate: true
      voxelsniper.brush.shellball: true
      voxelsniper.brush.shellset: true
      voxelsniper.brush.shellvoxel: true
      voxelsniper.brush.signoverwrite: true
      voxelsniper.brush.snipe: true
      voxelsniper.brush.snowcone: true
      voxelsniper.brush.spiralstaircase: true
      voxelsniper.brush.splatterball: true
      voxelsniper.brush.splatterdisc: true
      voxelsniper.brush.splatteroverlay: true
      voxelsniper.brush.splattervoxel: true
      voxelsniper.brush.splattervoxeldisc: true
      voxelsniper.brush.spline: true
      voxelsniper.brush.stamp: true
      voxelsniper.brush.stencil: true
      voxelsniper.brush.stencillist: true
      voxelsniper.brush.threepointcircle: true
      voxelsniper.brush.triangle: true
      voxelsniper.brush.underlay: true
      voxelsniper.brush.voltmeter: true
      voxelsniper.brush.voxel: true
      voxelsniper.brush.voxeldisc: true
      voxelsniper.brush.voxeldiscface: true
      voxelsniper.brush.warp: true
      voxelsniper.goto: true
      voxelsniper.sniper: true